# Generated by Django 3.1.7 on 2021-04-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_id', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('C_Fname', models.CharField(max_length=200)),
                ('C_Lname', models.CharField(max_length=200)),
                ('C_City', models.CharField(max_length=200)),
                ('C_Area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('D_id', models.IntegerField(default=201, primary_key=True, serialize=False)),
                ('D_Name', models.CharField(max_length=200)),
                ('D_time', models.DateTimeField()),
                ('D_totalCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('F_id', models.IntegerField(default=101, primary_key=True, serialize=False)),
                ('It_Name', models.CharField(max_length=200)),
                ('It_Kind', models.CharField(max_length=200)),
                ('It_Size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('R_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('R_Fname', models.CharField(max_length=200)),
                ('R_Lname', models.CharField(max_length=200)),
                ('R_Rating', models.IntegerField(default=1)),
                ('R_City', models.CharField(max_length=200)),
                ('R_Area', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_mobile', models.IntegerField()),
                ('Restaurant_Telephone', models.IntegerField()),
                ('Restaurant_Contact_pouplareName', models.CharField(default='The Contact Numbers', max_length=200)),
                ('Restaurant_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Restaurants Contacts',
            },
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.customer')),
                ('Delivery_id', models.ForeignKey(default=201, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.deliveryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.customer')),
                ('Food_it_id', models.ForeignKey(default=101, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='has',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_id', models.ForeignKey(default=201, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.deliveryinfo')),
                ('Food_it_id', models.ForeignKey(default=101, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='CustContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_mobile', models.IntegerField()),
                ('Customer_Telephone', models.IntegerField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_id', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.fooditem')),
                ('R_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.restaurant')),
            ],
        ),
    ]
