# Generated by Django 3.0.5 on 2021-04-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_id',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
        ),
    ]
