# Generated by Django 3.0.5 on 2021-04-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0002_auto_20210423_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restcontact',
            name='Restaurant_id',
        ),
        migrations.RemoveField(
            model_name='add',
            name='R_id',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestContact',
        ),
    ]
