# Generated by Django 3.0.5 on 2021-04-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0005_restaurant_r_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_Phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
