# Generated by Django 3.0.5 on 2021-04-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0006_auto_20210423_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurants'},
        ),
    ]
