# Generated by Django 3.0.5 on 2021-04-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0007_auto_20210423_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('F_id', models.IntegerField(default=101, primary_key=True, serialize=False)),
                ('It_Name', models.CharField(max_length=200)),
                ('It_Kind', models.CharField(max_length=200)),
                ('It_Size', models.CharField(max_length=200)),
            ],
        ),
    ]
