# Generated by Django 3.0.5 on 2021-04-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0008_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('D_id', models.IntegerField(default=201, primary_key=True, serialize=False)),
                ('D_Name', models.CharField(max_length=200)),
                ('D_time', models.DateTimeField()),
                ('D_totalCost', models.FloatField()),
            ],
        ),
    ]
