# Generated by Django 3.0.5 on 2021-04-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0010_has'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Fname', models.CharField(max_length=200)),
                ('C_Lname', models.CharField(max_length=200)),
                ('C_Email', models.EmailField(max_length=254)),
                ('C_Password', models.CharField(max_length=200)),
                ('C_Password2', models.CharField(max_length=200)),
                ('C_Phone', models.CharField(max_length=200)),
                ('C_City', models.CharField(max_length=200)),
                ('C_Area', models.CharField(max_length=200)),
            ],
        ),
    ]
