# Generated by Django 3.1.7 on 2021-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0013_order_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
    ]
