# Generated by Django 3.0.5 on 2021-04-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0014_auto_20210424_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It_Name', models.CharField(max_length=200)),
                ('It_Kind', models.CharField(max_length=200)),
                ('It_Size', models.CharField(max_length=200)),
            ],
        ),
    ]
