# Generated by Django 3.1.7 on 2021-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0015_fooditem_f_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_id',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
    ]
