# Generated by Django 3.0.5 on 2021-04-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0015_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='F_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.FoodItem'),
        ),
    ]
