# Generated by Django 3.1.7 on 2021-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0016_auto_20210424_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
