# Generated by Django 3.0.5 on 2021-04-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0017_has_food_it_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Food_it_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.FoodItem'),
        ),
    ]
