# Generated by Django 3.0.5 on 2021-04-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0018_order_food_it_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has',
            name='Delivery_id',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='Delivery_id',
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
    ]
