# Generated by Django 3.0.5 on 2021-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0021_auto_20210424_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
