# Generated by Django 3.0.5 on 2021-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0022_auto_20210424_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='R_Email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Phone',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
