# Generated by Django 3.0.5 on 2021-04-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0025_auto_20210425_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Restaurants'},
        ),
    ]
