# Generated by Django 3.0.5 on 2021-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0026_auto_20210425_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='C_Email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='C_Phone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
