# Generated by Django 3.1.7 on 2021-04-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0028_auto_20210425_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
    ]
