# Generated by Django 3.1.7 on 2021-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0028_auto_20210425_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='It_Descrip',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
