# Generated by Django 3.1.7 on 2021-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0029_auto_20210426_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='F_Images',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Image',
        ),
    ]
