# Generated by Django 3.1.7 on 2021-04-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0029_fooditem_it_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='It_Prise',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
