# Generated by Django 3.1.7 on 2021-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0031_restaurant_r_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
    ]
