# Generated by Django 3.1.7 on 2021-04-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0032_fooditem_f_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Image',
        ),
    ]
