# Generated by Django 3.1.7 on 2021-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0037_remove_fooditem_it_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='It_Descrip',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
