# Generated by Django 3.1.7 on 2021-04-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0038_fooditem_overs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='overs',
            new_name='F_Rate',
        ),
    ]
