# Generated by Django 3.1.7 on 2021-04-27 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0039_auto_20210427_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_Rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
