# Generated by Django 3.1.7 on 2021-04-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0040_restaurant_r_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Rate',
        ),
    ]
