# Generated by Django 3.1.7 on 2021-04-27 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0041_remove_restaurant_r_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='R_Rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
