# Generated by Django 3.0.5 on 2021-04-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0043_merge_20210427_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Area',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Type',
            field=models.CharField(max_length=150),
        ),
    ]
