# Generated by Django 3.0.5 on 2021-04-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0045_restaurant_r_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null.png', upload_to='media/images'),
        ),
    ]
