# Generated by Django 3.1.7 on 2021-04-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0047_auto_20210428_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=200)),
                ('Mkind', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='RImage_Cover',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=200)),
                ('Scity', models.CharField(max_length=200)),
                ('provide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.meal')),
            ],
        ),
    ]
