# Generated by Django 3.1.7 on 2021-05-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0048_auto_20210430_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='provide',
        ),
        migrations.CreateModel(
            name='khod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.meal')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.shop')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='shops',
            field=models.ManyToManyField(through='fastfoodapp.khod', to='fastfoodapp.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='meals',
            field=models.ManyToManyField(through='fastfoodapp.khod', to='fastfoodapp.meal'),
        ),
    ]
