# Generated by Django 3.1.7 on 2021-05-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0049_auto_20210502_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='shops',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='meals',
        ),
        migrations.DeleteModel(
            name='khod',
        ),
        migrations.DeleteModel(
            name='meal',
        ),
        migrations.DeleteModel(
            name='shop',
        ),
    ]
