# Generated by Django 3.1.7 on 2021-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0050_auto_20210502_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vindour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vname', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('foods', models.ManyToManyField(to='fastfoodapp.food')),
            ],
        ),
    ]
