# Generated by Django 3.1.7 on 2021-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0051_food_vindour'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='foods',
            field=models.ManyToManyField(to='fastfoodapp.Restaurant'),
        ),
    ]
