# Generated by Django 3.1.7 on 2021-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0052_fooditem_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has',
            name='Delivery_id',
        ),
        migrations.RemoveField(
            model_name='has',
            name='Food_it_id',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='Delivery_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Food_it_id',
        ),
        migrations.AddField(
            model_name='order',
            name='D_Name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='D_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='D_totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ManyToManyField(to='fastfoodapp.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(to='fastfoodapp.Restaurant'),
        ),
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
        migrations.DeleteModel(
            name='has',
        ),
        migrations.DeleteModel(
            name='Receive',
        ),
    ]
