# Generated by Django 3.1.7 on 2021-05-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0053_auto_20210504_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindour',
            name='foods',
        ),
        migrations.DeleteModel(
            name='food',
        ),
        migrations.DeleteModel(
            name='vindour',
        ),
    ]
