# Generated by Django 3.1.7 on 2021-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0054_auto_20210504_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(to='fastfoodapp.FoodItem'),
        ),
    ]
